# Generated by Django 5.0 on 2025-06-18 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_admin', '0002_invoice_other_invoice_other_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-bill_date', '-bill_created_at']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bottle_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='jug_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10),
        ),
    ]
